### ISSUE TITLE
Incorrect Content-Type: application/json;

### ISSUE THREAD

**Issue by DavidDeSloovere** [TimothyMeadows/reCAPTCHA.AspNetCore#104]
Lately we've been getting a lot exception for this error. Probably an error on recaptcha's server that was returned, instead of valid json.
It's not handled in `reCAPTCHA.AspNetCore.RecaptchaService+<Validate>`
Would be great if there was a retry, or if we could pass in an HttpClient (typed to CaptchaService maybe?).

Is this project still active? Accepting PRs?

**Comment by DavidDeSloovere** [comment]
We traced it down to this file/class, at line 104.
https://github.com/dotnet/aspnetcore/blob/main/src/Http/Http/src/Features/FormFeature.cs

The post was altered by a bot/hacker to have an incorrect content type.
I think this lib should capture this and maybe return as invalid response.

**Comment by TimothyMeadows** [comment]
Project was not active at the time of request. Closing for now and will work to address additional concerns in future net8 version.
