### ISSUE TITLE
Proxy Support

### ISSUE THREAD

**Issue by mike2212** [TimothyMeadows/reCAPTCHA.AspNetCore#13]
Currently using on a .net core 2.2 project (running under windows).  There appears to be no way to use this project via a proxy?  

I believe under 2.0 the "internet options" proxy was automatically defined in the HttpClient.  I guess this changed in 2.1 along with the inclusion of the [HttpClientFactory](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-2.1)?

Thanks in advance, 
Mike

**Comment by TimothyMeadows** [comment]
RecaptchaService supports an HttpClient constructor. You can create your own client, and pass it to the service before creation. I recommend creating and passing your own static HttpClient as pointed out here #9

I can't actual speak to any HttpClient changes between versions for the proxy feature in .NET.
