### ISSUE TITLE
NetStandard

### ISSUE THREAD

**Issue by ruben0909** [TimothyMeadows/reCAPTCHA.AspNetCore#14]
Hi,

Thank you for your awesome work.
I have a dotnet core projet with Target Full Framework 4.7.2. 
Is it possible have an updated version of this package for .NET Standard Projects? 
The Current version is not working with v3, because of the response is undefined, I saw is corrected, but not in .NET Standard version, (The latest available version in nuget.org is 2.1.1)

Thnak you again.

**Comment by TimothyMeadows** [comment]
Hi current version on github does actually support .NET Standard 2.0 (PR from a user). I have not validated it yet however to release on Nuget. I will try and get to this as soon as time permits.

**Comment by ruben0909** [comment]
@TimothyMeadows  Thank you.

**Comment by TimothyMeadows** [comment]
Sorry for the delay. This has now been resolved with the latest version.

**Comment by ruben0909** [comment]
Hi @TimothyMeadows 

Thank you for your awesome work .
