### ISSUE TITLE
Tag attributes and grecaptcha.render parameters

### ISSUE THREAD

**Issue by Aurora7Sys** [TimothyMeadows/reCAPTCHA.AspNetCore#19]
It would be nice to be able to specify some aspects of how the reCaptcha displays such as:

data-theme | theme | dark light | The color theme of the widget.
data-size | size | compact normal | The size of the widget.

From this page:
https://developers.google.com/recaptcha/docs/display#config

Thank you for considering this!

**Comment by TimothyMeadows** [comment]
The only thing i can support is theme which you can set using the Recaptcha helper. See the theme property in your intellisense.
