### ISSUE TITLE
Not complete readme

### ISSUE THREAD

**Issue by andreysozontov** [TimothyMeadows/reCAPTCHA.AspNetCore#2]
Hello, and big thanks for your package, I really like it!
Could you add something to your readme?
`<script src="https://www.google.com/recaptcha/api.js" async defer></script>
` - developer also must include this to his layout or view
And to add this `@inject IOptions<RecaptchaSettings> RecaptchaSettings` to his view he also must add using directive before, like `@using Microsoft.Extensions.Options;`

**Comment by TimothyMeadows** [comment]
This will be added in the next release. The initial idea was to allow the package to add that script for you however time has not permitted me to add this feature yet. In the men time i will update the docs to reflect your information.

Thank you.

**Comment by TimothyMeadows** [comment]
[6e9ce97bbc1db5da37b76599e0bfb078e397b851](https://github.com/TimothyMeadows/reCAPTCHA.AspNetCore/commit/6e9ce97bbc1db5da37b76599e0bfb078e397b851)
