### ISSUE TITLE
Recaptcha host and request host do not match. Forgery attempt? v2-invis or v3

### ISSUE THREAD

**Issue by accarvajal** [TimothyMeadows/reCAPTCHA.AspNetCore#20]
Hi,

I'm using v2.1.1 due to my ASP.Net Core is version 2.1, giving me troubles with upper versions. I need to use invisible captcha v2-invisible or V3, I tried to follow documentation, follow is Startup:
```
var recaptcha = Configuration.GetSection("RecaptchaSettings");
            if (!recaptcha.Exists())
                throw new ArgumentException("Missing RecaptchaSettings in configuration.");

services.Configure<RecaptchaSettings>(Configuration.GetSection("RecaptchaSettings"));
services.AddTransient<IRecaptchaService, RecaptchaService>();
```

Following is login view:

`<form asp-area="Identity" asp-controller="Account" asp-action="Login" method="post" class="ffl-form" id="loginForm">
                            <h3>@Localizer["Ingrese al portal de SicotX"]</h3>
                            <h6>@Localizer["con sus Credenciales"]</h6>
                            <hr />
                            <div class="form-group">
                                <div class="ffl-wrapper">
                                    <label asp-for="Usuario" class="ffl-label">@Localizer["Usuario"]</label>
                                    <input asp-for="Usuario" class="form-control" autocomplete="off" />
                                    <span asp-validation-for="Usuario" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="ffl-wrapper">
                                    <label asp-for="Contraseña" class="ffl-label">@Localizer["Contraseña"]</label>
                                    <input asp-for="Contraseña" class="form-control" />
                                    <span asp-validation-for="Contraseña" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.Recaptcha(RecaptchaSettings?.Value)
                            </div>
                            <div class="form-group text-center">
                                <button id="recaptcha" type="submit" class="btn btn-primary">@Localizer["Ingresar"] <i class="fa fa-user"></i></button>
                            </div>
                        </form>`

Following is Account controller for Login action:

`public async Task<IActionResult> Login(LoginViewModel model)
        {
            var recaptcha = await _recaptcha.Validate(Request);
            if (!recaptcha.success)
            {
                ModelState.AddModelError("Error", _localizer["Hubo un error de validación del Captcha. Por favor intente nuevamente!"].Value);
                _logger.LogInformation($"Hubo un error de validación del Captcha.");
            }
`
I configured appSettings (I created 2 sites for v2 invisible and v3) with the correct sitekey and secretkey and version: v2-invis and throws the exception, as follows:

ValidationException: Recaptcha host, and request host do not match. Forgery attempt?
reCAPTCHA.AspNetCore.RecaptchaService.Validate(HttpRequest request, bool antiForgery) in RecaptchaService.cs
SicotX.Areas.Identity.Controllers.AccountController.Login(LoginViewModel model) in AccountController.cs
+
            var recaptcha = await _recaptcha.Validate(Request);
Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor+TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, object controller, object[] arguments)
System.Threading.Tasks.ValueTask<TResult>.get_Result()
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
SicotX.Startup+<>c+<<Configure>b__6_1>d.MoveNext() in Startup.cs
+
                await next();
SicotX.Startup+<>c+<<Configure>b__6_0>d.MoveNext() in Startup.cs
+
                await next();
Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

I changed to correct sitekey and secretkey and v3 but for some reason my submit button dissapeared, no way to click on Login button, and javascript error is thrown:

Uncaught Error: reCAPTCHA placeholder element must be an element or id
    at Object.Fd [as render] (www.gstatic.com/recaptcha/api2/v1554100419869/recaptcha__es_419.js:526)
    at _eebca1b4_7f0d_4e74_b2e9_d5fba0580a53 (Login:268)
    at $p (www.gstatic.com/recaptcha/api2/v1554100419869/recaptcha__es_419.js:516)
    at iG (www.gstatic.com/recaptcha/api2/v1554100419869/recaptcha__es_419.js:517)
    at www.gstatic.com/recaptcha/api2/v1554100419869/recaptcha__es_419.js:530
    at www.gstatic.com/recaptcha/api2/v1554100419869/recaptcha__es_419.js:549

I don't know if I'm following nuget package documentation it not works. What am I doing wrong?

I would prefer to use V3, but not succeded. Thanks for any help!

**Comment by TimothyMeadows** [comment]
Hi, there a few reasons this can occur. The first was i think a bug might have existed in this version that was including port number with host name in non-standard situations (such as running in IIS Express). The other is that your using some sort of proxy, or hosting situation in which the domain that google returns from the recaptcha key, and the one your actually hosting on don't match.

In the event this is because of a bug, or if it's a forgery issue you can't resolve. You can simply turn this feature off by setting antiForgery to false with the Reacaptcha helper method. This will prevent the check from occurring at all.

Finally, the latest version of this library no longer targets .NET Core specifically. Rather, it now targets .NET Standard 2.0 which should work in any version of .NET Core 2.x, and most versions of .NET framework (I think 4.6+?)

**Comment by TimothyMeadows** [comment]
Sorry to correct one error above. The actual antiForgery boolean is on the Validation method in your controller and not actually in the view options. My apologies for the mistake.

**Comment by accarvajal** [comment]
Thanks, I could solved, I migrated my Asp.Net core 2.1 solution to 2.2 which let me update reCaptcha nuget package to the last version available and with those things reCaptcha worked fine! It seems migrating to 2.2 its better than try to find a workaround about it with older nuget package.

**Comment by MikeRixWolfe** [comment]
How is the antiForgery meant to be set? 

In my markdown I have `@(Html.Recaptcha<RecaptchaV2Checkbox>(RecaptchaSettings.Value, new RecaptchaV2Checkbox { SuccessCallback = "enableSubmit", ExpiredCallback = "disableSubmit" }))` and on my controller I use the annotation `[ValidateRecaptcha(score: 0.7)]` and neither of these take in a antiForgery argument.
