### ISSUE TITLE
recaptcha v3 in ajax form refresh

### ISSUE THREAD

**Issue by rbsdotnet** [TimothyMeadows/reCAPTCHA.AspNetCore#25]
Hi,
How to refresh Recaptcha when cannot login in ajx form
For Example:
[New Text Document.txt](https://github.com/TimothyMeadows/reCAPTCHA.AspNetCore/files/3446838/New.Text.Document.txt)

**Comment by TimothyMeadows** [comment]
This issue is specific to your application and i can't help with it. Sorry.
