### ISSUE TITLE
Set data-badge property to inline

### ISSUE THREAD

**Issue by genii90** [TimothyMeadows/reCAPTCHA.AspNetCore#26]
The default location for data-badge property for v2-invis is bottomright. I am having a problem with default location because it ends up being obscured by my footer. This runs contrary to the terms of service of using captcha. (See discussion here: https://stackoverflow.com/questions/44543157/how-to-hide-the-google-invisible-recaptcha-badge). 
Is there anyway to specify data-badge to be inline?

**Comment by genii90** [comment]
A workaround would be put to set the z-index of the footer to -1.

**Comment by TimothyMeadows** [comment]
I don't actually control the location via the library. However you could handle this with CSS. I am not sure if the violate terms if you changes where google decided it should go /shrug
