### ISSUE TITLE
Using Webproxy

### ISSUE THREAD

**Issue by DavidStania** [TimothyMeadows/reCAPTCHA.AspNetCore#28]
Hey,
i've got an error while valdiation process, cause webserver using a webproxy. How to configure proxy for valdiation process?
Best regards.
David

**Comment by TimothyMeadows** [comment]
You can add proxy settings to the HttpClient object, You can find the static HttpClient object on RecaptchaService.Client. You can read more in the HttpClient docs. https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.defaultproxy?view=netcore-3.0

**Comment by TimothyMeadows** [comment]
If you find there is an issue with the library it's self please feel free to reopen this issue, or create a new one.
