### ISSUE TITLE
Pre-release for the callback support

### ISSUE THREAD

**Issue by Tri125** [TimothyMeadows/reCAPTCHA.AspNetCore#30]
Hi. Would it be possible to have a nugget release/pre-release to get the newly introduced callback support? If not, when can we expect the next nugget release?

**Comment by Tri125** [comment]
Upon reviewing the code I came to realize that it was only introduced in v2. So my question would be when is it going to be added to v3 and then released?

I'm using the library to do recaptcha v3 validation and due to browsers pre-filling forms it's possible for users to submit the form before recaptcha has done loading or getting the token. Having a callback would let us know when the user can submit the correctly form.

**Comment by javidgahramanov** [comment]
I have solved the callback problem by adding **data-callback** attribute manually.

`$('.g-recaptcha').attr("data-callback", "recaptcha_callback");`

` function recaptcha_callback() 
 {
   $('#RecaptchaError').hide();
 }`

**Comment by TimothyMeadows** [comment]
This has been updated in 2.2.5 however you will still need to add the attribute yourself as shown above. I am just noting this in case anyone is stuck using the older version of the package and still needs this. This will be correctly addressed in future 3.x versions. Sorry for the trouble.
