### ISSUE TITLE
Question: How to skip validation on local environment?

### ISSUE THREAD

**Issue by Marusyk** [TimothyMeadows/reCAPTCHA.AspNetCore#33]
I'm using this library and it works perfect, on production. How can I disable for localhost?

Thank you in advance

**Comment by carlin-q-scott** [comment]
@Marusyk Did you figure it out? I extended some of the library classes to optionally disable it via RecaptchaSettings, but perhaps there's an easier way?

**Comment by Marusyk** [comment]
Thanks,

For now, I've added localhost to domain at google, and use Recaptcha for localhost.  But it would be great to have some settings like:

```json
"RecaptchaSettings": {
    "Enabled": true,
    "SecretKey": "paste secret key here",
    "SiteKey": "paste site key here",
    "Version": "v2"
  } 
```

**Comment by carlin-q-scott** [comment]
@Marusyk That's the exact setting I added. I'll tidy up my code and create a PR.
