### ISSUE TITLE
V2.TransformText  V3.TransformText didn't use domain by UseRecaptchaNet

### ISSUE THREAD

**Issue by jafsuen** [TimothyMeadows/reCAPTCHA.AspNetCore#35]
V2.TransformText  V3.TransformText didn't use domain in address.
Like this:
var domain = UseRecaptchaNet ? "www.recaptcha.net" : "www.google.com";

**Comment by TimothyMeadows** [comment]
Thanks for the report, this should be resolved in 2.2.5 if it's still an issue please reopen for consideration in the new 3.x version.
