### ISSUE TITLE
Support for Asp Core 3

### ISSUE THREAD

**Issue by prince272** [TimothyMeadows/reCAPTCHA.AspNetCore#36]

**Comment by prince272** [comment]
I know it works well with asp core 3 but don't you have to update the dependencies.

**Comment by iunknown21** [comment]
Has anyone has success with Asp.Net 3.0?  
I'm getting 'ValidateRecaptcha' not found error.

I'm using version 2.2.3

**Comment by TimothyMeadows** [comment]
No, this has only been designed for 2.2, i have been working on 3.1 support for MVC but i have not had the time to manage it lately. Hopefully soon...

**Comment by iunknown21** [comment]
Thank you for the update Timothy.

**Comment by prince272** [comment]
Any updates so far?

**Comment by TimothyMeadows** [comment]
Hi, thanks to down time from the Corona virus i now have time to port this to 3.x. I have released 2.2.5 today including various community updates / fixes not made by me. This is the final release of this package for .NET core 2.x. This version will be moved to it's own branch.
