### ISSUE TITLE
Support for multiple reCAPTCHA forms.

### ISSUE THREAD

**Issue by prince272** [TimothyMeadows/reCAPTCHA.AspNetCore#37]

**Comment by TimothyMeadows** [comment]
Each recaptcha form has it's own unqiue id, you can use as many as you like.

**Comment by carlin-q-scott** [comment]
The ids are not unique.
![image](https://user-images.githubusercontent.com/2521644/85332259-7b94ec80-b48c-11ea-892a-164d96182bd3.png)

Only the first recaptch input gets the token value.

Also, there are also multiple .rc-anchors present on the page.
