### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by michalss** [TimothyMeadows/reCAPTCHA.AspNetCore#44]
Hi im trying to implement it but getting 

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'ValidateRecaptcha' could not be found (are you missing a using directive or an assembly reference?)	SSS	D:\Private\Projects\c#\=WWW=\SSS\SSS\Controllers\usersController.cs	151	Active
```

No matter what this is always the outcome.. :(

**Comment by mengyg** [comment]
it seems ValidateRecaptchaAttribute is not included in the 2.2.3

**Comment by CloudSmithIra** [comment]
I got the same result as @mengyg

**Comment by aseniah** [comment]
Same issue. Missing ValidateRecaptchaAttribute in 2.2.3.
It looks like this change was merged in on 2/12/20 (along with README updates) and 2.2.3 was released on 4/15/19. The README does not represent 2.2.3.

The README at the time of 2.2.3 release shows how to validate without the attribute.
https://github.com/TimothyMeadows/reCAPTCHA.AspNetCore/blob/7b56d96386a6cbeff97c80ff071b1da98bdd7050/README.md

**Comment by bonioloa** [comment]
2.2.3 helper also does not include callback methods parameters

**Comment by timotyturini** [comment]
Looks like kind of package building issue: @TimothyMeadows can you straightly release the same codebase into 2.2.4 version? Pay attention for cached assemblies before release the nupkg

**Comment by TimothyMeadows** [comment]
This should now be updated to included changes that where not made by me in version 2.2.5
