### ISSUE TITLE
Support for Razor Pages

### ISSUE THREAD

**Issue by Atulin** [TimothyMeadows/reCAPTCHA.AspNetCore#45]
As it stands, `[ValidateRecaptcha]` cannot be added to a Razor Page's `OnPost` or `OnPostAsync` method.

Is there any other way to verify the captcha response that isn't included in the readme?

**Comment by TimothyMeadows** [comment]
Yes. You can create an inject an instance of the RecaptchaService class into the razor page. You can then call the validation method directly rather then using the attribute. https://github.com/TimothyMeadows/reCAPTCHA.AspNetCore/blob/master/reCAPTCHA.AspNetCore/RecaptchaService.cs#L62-L71
