### ISSUE TITLE
recaptcha v3

### ISSUE THREAD

**Issue by zmarsel1** [TimothyMeadows/reCAPTCHA.AspNetCore#5]
grecaptcha is always undefined. is inialization of recatcha api must go before checking grecaptcha in templates?

**Comment by TimothyMeadows** [comment]
Was able to reproduce this, looks like Recatpcha v3 was taken out of beta recently as well. Will be updating later today with a fix. Thanks for the report!

**Comment by TimothyMeadows** [comment]
https://github.com/TimothyMeadows/reCAPTCHA.AspNetCore/commit/ee4df3068967240235c069c050b9ab0eb9e61abe
