### ISSUE TITLE
how to I set language  in new version of reCAPTCHA.

### ISSUE THREAD

**Issue by sonsy-soft** [TimothyMeadows/reCAPTCHA.AspNetCore#52]
Dear Timothy
How Can we set language  of reCAPTCHA V3 ?
I want another language like fa.

**Comment by TimothyMeadows** [comment]
By using the property for Language in the matching model. Example:

```csharp
@(Html.Recaptcha<RecaptchaV2Checkbox>(RecaptchaSettings?.Value, new RecaptchaV2Checkbox { Language = "en") })
```

**Comment by sonsy-soft** [comment]
Thanks Meadows .
but i have error on V3 HiddenInput that about setting class.
what shoukd i do?
