### ISSUE TITLE
How do we change the action value.

### ISSUE THREAD

**Issue by iBasisLtd** [TimothyMeadows/reCAPTCHA.AspNetCore#53]
Hi
How to change the Action attribute from 'homepage'.?

	if (typeof grecaptcha !== 'undefined') {
		grecaptcha.ready(function () {
			grecaptcha.execute('fbfbfbfbfbfbfbfbfbfbfbfbfbfbfbfbf', { 'action': 'homepage' }).then(function (token) {
				document.getElementById('g-recaptcha-response').value = token;
			});
		});
	}

**Comment by TimothyMeadows** [comment]
You shouldn't be using script but rather the helper as shown below.

```csharp
@(Html.Recaptcha<RecaptchaV3HiddenInput>(RecaptchaSettings?.Value, new RecaptchaV3HiddenInput { Action = "Homepage" }))
```
