### ISSUE TITLE
Invisible ReCaptcha

### ISSUE THREAD

**Issue by soad1820** [TimothyMeadows/reCAPTCHA.AspNetCore#55]
Hello,

Do you have an example of using the invisible version of ReCaptcha?

Thanks

**Comment by TimothyMeadows** [comment]
Just replace T when calling Recaptcha in your view with the version you want. The rest is the same as the example in the repo for checkbox.

For example replace:
```csharp
@(Html.Recaptcha<RecaptchaV2Checkbox>(RecaptchaSettings?.Value))
```

With this for V2 hidden input:

```csharp
@(Html.Recaptcha<RecaptchaV2Invisible>(RecaptchaSettings?.Value))
```

The rest of the example is valid regardless of the client-side version you have chosen.
