### ISSUE TITLE
Translate error messages?

### ISSUE THREAD

**Issue by woeterman94** [TimothyMeadows/reCAPTCHA.AspNetCore#57]
I'm using this in an application which has multilanguage support. Is there a way to translate or localize the error messages?

`There was an error validating the google recaptcha response. Please try again, or contact the site owner.`

**Comment by TimothyMeadows** [comment]
Yes, this can be done using the errorMessage overload on the ValidateRecaptcha attribute.

```csharp
[ValidateRecaptcha(0, "My custom error message here")]
```
