### ISSUE TITLE
false antiforgery exception

### ISSUE THREAD

**Issue by JoshScan** [TimothyMeadows/reCAPTCHA.AspNetCore#6]
when testing and the captcha hostname is set to local host it throws on lione 34 of RecaptchaServices.cs because e.g. localhost != localhost:12345 
looks like code should test against request.Host.Host.ToLower()

**Comment by TimothyMeadows** [comment]
Hmm, interesting condition I'm not sure you can actually even use recaptcha from localhost anyway? It's fair to say anyone hosting on a none-standard port will have the same issue though. I also notice you put in a pull request for this.

**Comment by TimothyMeadows** [comment]
I have merged your pull request. Thank you for the bug report, and the patch. Contributions are always appreciated!

https://github.com/TimothyMeadows/reCAPTCHA.AspNetCore/commit/6b76762e4a27a2a4a1f80efde281036c72fa8289
https://www.nuget.org/packages/reCAPTCHA.AspNetCore/2.1.2
