### ISSUE TITLE
[ValidateRecaptcha] 

### ISSUE THREAD

**Issue by utech626** [TimothyMeadows/reCAPTCHA.AspNetCore#66]
The attribute works on Controllers but not Razor Pages. Identity framework uses razor pages for login and logout

**Comment by TimothyMeadows** [comment]
You can inject IRecaptchaService into the page and call it yourself. Edge cases such as identity, or custom code are up to the developer to choose how to support. Attributes are only there to make things easy for standard environments. Links below to help you reproduce your own usage.

https://github.com/TimothyMeadows/reCAPTCHA.AspNetCore/blob/master/reCAPTCHA.AspNetCore/Attributes/ValidateRecaptchaFilter.cs

https://github.com/TimothyMeadows/reCAPTCHA.AspNetCore/blob/master/reCAPTCHA.AspNetCore/RecaptchaService.cs#L27-L52

**Comment by TimothyMeadows** [comment]
Modified example can be found here for non-standard usage

https://github.com/TimothyMeadows/reCAPTCHA.AspNetCore/commit/f3ca99080e06cc2d5a187e29891d0c05518a8db7
