### ISSUE TITLE
Could not load type 'Microsoft.AspNetCore.Http.Internal.BufferingHelper

### ISSUE THREAD

**Issue by tank104** [TimothyMeadows/reCAPTCHA.AspNetCore#68]
I have installed this package, and it works well thanks!

I have this issue though where a lot of unit tests are failing with this error:
System.TypeLoadException : Could not load type 'Microsoft.AspNetCore.Http.Internal.BufferingHelper' from assembly 'Microsoft.AspNetCore.Http, Version=3.1.4.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.

I am using netcoreapp3.1 framework, and don't really understand how your package causes this issue since there are no dependencies, however when I remove your package its fine again.

Any help appreciated.

**Comment by TimothyMeadows** [comment]
That's strange. I've never seen such an error with the library. I'm not aware of referencing those libraries. The library does depend on HttpClient https://github.com/TimothyMeadows/reCAPTCHA.AspNetCore/blob/master/reCAPTCHA.AspNetCore/RecaptchaService.cs#L12 but that's the only requirement for http that exists that i am aware of.

There may be a specific configuration in your environment that has internal buffering disabled for httpclient?

**Comment by tank104** [comment]
Its really weird, I can't figure it out, and don't know enough about the new Microsoft.AspNetCore.Http library to know.

I have tried adding Framework reference in both main and test project with no luck:
```
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

```
Why do you need to use Microsoft.AspNetCore.Http though? the code you showed me uses HttpClient from System.Net.Http.  Just wondered if you needed it at all?

**Comment by TimothyMeadows** [comment]
The project doesn't reference it directly. Quick google search show it's part of HttpRequest maybe? It seems like you have unique environment / requirements which falls on you to satisfy. This is not a general problem or error or it would be felt by the many projects that depend on this library. Though i will leave this issue up for anyone else that might have more information that might help.

**Comment by tank104** [comment]
@TimothyMeadows thanks for the feedback.
Looks like issue was in one of the packages I was referencing.  It used ReadAsStringAsync() an extension for HttpRequest, that I guess is not compatible with 3.1 or some issue.
This helped:
https://stackoverflow.com/questions/59466227/could-not-load-type-microsoft-aspnetcore-http-internal-bufferinghelper-from-as

Basically changing that method from using request.EnableRewind to request.EnableBuffering() sorted it.

I am still not sure why your package caused the issue (perhaps it forced 3.1 AspNetCore, where as it was falling back to previous version before.  Nuget/DLL hell! 

Anyway hope this helps someone..

**Comment by TimothyMeadows** [comment]
Interesting indeed. Closing this now, will point others to it if they run into the same issue.
