### ISSUE TITLE
Use of disposed HttpClient in RecaptchaService

### ISSUE THREAD

**Issue by rustybox** [TimothyMeadows/reCAPTCHA.AspNetCore#70]
```
<PackageReference Include="reCAPTCHA.AspNetCore" Version="3.0.6" />
```

Sorry this is a naff bug report, bit busy or I would try to be more thorough.

I think it's on second instantiation of RecaptchaService, you register service transient but don't always new up a HttpClient (it's static) so you can keep around one which has been disposed.

I already have a dependency on Flurl.Http which gives me a nice abstraction around HttpClient and manages client lifetimes for me per domain so I have just registered a new IRecaptchaService

```csharp
using System.ComponentModel.DataAnnotations;
using System.Net.Http;
using System.Threading.Tasks;
using Flurl.Http;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Options;
using reCAPTCHA.AspNetCore;

namespace Foo.Example.Com
{

    public class HackRecaptchaService : IRecaptchaService
    {
        private readonly RecaptchaSettings _settings;

        public HackRecaptchaService(IOptions<RecaptchaSettings> options)
        {
            _settings = options.Value;
        }

        public HackRecaptchaService(IOptions<RecaptchaSettings> options, HttpClient client)
        {
            _settings = options.Value;
        }

        public async Task<RecaptchaResponse> Validate(HttpRequest request, bool antiForgery = true)
        {
            if (!request.Form.ContainsKey("g-recaptcha-response")) // error if no reason to do anything, this is to alert developers they are calling it without reason.
                throw new ValidationException("Google recaptcha response not found in form. Did you forget to include it?");

            var response = request.Form["g-recaptcha-response"];
            var url = $"https://{_settings.Site}/recaptcha/api/siteverify?secret={_settings.SecretKey}&response={response}";
            var captchaResponse = await url.GetJsonAsync<RecaptchaResponse>();


            if (!captchaResponse.success || !antiForgery) 
                return captchaResponse;

            var sameHost = captchaResponse.hostname.Equals(request.Host.Host, StringComparison.OrdinalIgnoreCase);
            var testHost = captchaResponse.hostname.Equals("testkey.google.com", StringComparison.OrdinalIgnoreCase);

            if (!sameHost && !testHost)
            {
                throw new ValidationException("Recaptcha host, and request host do not match. Forgery attempt?");
            }

            return captchaResponse;
        }

        public async Task<RecaptchaResponse> Validate(string responseCode)
        {
            if (string.IsNullOrEmpty(responseCode))
                throw new ValidationException("Google recaptcha response is empty?");

            var url = $"https://{_settings.Site}/recaptcha/api/siteverify?secret={_settings.SecretKey}&response={responseCode}";
            var captchaResponse =  await url.GetJsonAsync<RecaptchaResponse>();
            return captchaResponse;
        }
    }
}

```

**Comment by TimothyMeadows** [comment]
I guess as i might understand your question. This isn't an actual bug. It's recommended to practice to keep HttpClient around and NOT to recreate it on each call. There is a check if HttpClient is empty in which case it's created only once. https://github.com/TimothyMeadows/reCAPTCHA.AspNetCore/blob/master/reCAPTCHA.AspNetCore/RecaptchaService.cs#L18

**Comment by rustybox** [comment]
Indeed, one should keep a single http client around per host if possible, this is what Flurl.Http does.

However what one shouldn’t attempt to do, is make a http request with a disposed HttpClient instance as that just throws exceptions, that is what this bug report is about.

**Comment by rustybox** [comment]
It's the second constructor, not sure why a HttpClient is registered in the container, it's an IdentityServer4 project so maybe something upstream.

Should the second constructor exist, what's its purpose?

```csharp
public RecaptchaService(IOptions<RecaptchaSettings> options, HttpClient client)
{
    RecaptchaSettings = options.Value;
    Client = client;
}
```

**Comment by TimothyMeadows** [comment]
The purpose is from an older version of this library, it's there mostly for historical value, though it can be used to supply your own HttpClient rather than letting the library create it for you. I can look into the effect of removing it.

**Comment by TimothyMeadows** [comment]
I don't see any adverse effects of removing this, i doubt anyone uses HttpClient publicly, or set's it via the constructor. If they did i doubt it would cause harm, "not" doing so.

I did add a comment to your pull request though. You had made RecaptchaSettings private, but i do actually know of users that depend on this being public. It would be better to change that back to public and i can approve. Appreciate the work / pull request.
