### ISSUE TITLE
Remove asynchronous script call

### ISSUE THREAD

**Issue by kingzfate** [TimothyMeadows/reCAPTCHA.AspNetCore#74]
Hello, in my project I have1 problem. When I loading form with 
`@(Html.Recaptcha<RecaptchaV3HiddenInput>(RecaptchaSettings.Value)`
ReCaptcha token don't insert to  `<input id="<#= Model.Id #>" name="g-recaptcha-response" type="hidden" value="" />`
when "async defer" enabled.
I need a fix.
I solved that problem like this, please accept the changes.
RecaptchaV3HiddenInput.cs
`
public class RecaptchaV3HiddenInput : RecaptchaVersion
    {
        public string Id { get; set; } = "g-recaptcha-response";
        public string Action { get; set; } = "homepage";
        public bool IsAsync { get; set; } = true;
    }`
"RecaptchaV3HiddenInput.tt"
`<script <# if (!string.IsNullOrEmpty(Model.Settings.ContentSecurityPolicy)) {#>script-src="<#= Model.Settings.ContentSecurityPolicy #>"<#}#> <# if (!string.IsNullOrEmpty(Model.Settings.ContentSecurityPolicy)) {#>frame-src="<#= Model.Settings.ContentSecurityPolicy #>"<#}#> src="https://<#= Model.Settings.Site #>/recaptcha/api.js?render=<#= Model.Settings.SiteKey #>&hl=<#= Model.Language #>" <# if (Model.IsAsync) {#>async defer<#}#> ></script>`

And then we can choose whether to load them asynchronously

**Comment by TimothyMeadows** [comment]
Can you turn this into a pull request so i can accept your work? This is a nice fix i would have issue publishing it.

**Comment by kingzfate** [comment]
Yes, I created it. Thx!

**Comment by TimothyMeadows** [comment]
Approved, and updated in 3.0.9.
