### ISSUE TITLE
How can I change recaptcha language?

### ISSUE THREAD

**Issue by itsolutionnow** [TimothyMeadows/reCAPTCHA.AspNetCore#8]
In google recaptcha, there's hl attribute which shows language.
<script src="https://www.google.com/recaptcha/api.js?explicit&hl=nl"></script> 

How can I use this feature?

**Comment by TimothyMeadows** [comment]
Support for language codes has now been added in version 2.1.3. Thank you for the submission. https://github.com/TimothyMeadows/reCAPTCHA.AspNetCore/releases/tag/2.1.3

**Comment by itsolutionnow** [comment]
How can I use it?
Can you provide doc or demo?

**Comment by TimothyMeadows** [comment]
You will find a new parameter when creating the service named language. You can use one of the codes from here: https://developers.google.com/recaptcha/docs/language

Here is an example:

```@Html.Recaptcha(RecaptchaSettings?.Value, language:"nl")```
