### ISSUE TITLE
Using it in Ajax form, unvalid modelstate

### ISSUE THREAD

**Issue by hphilbert** [TimothyMeadows/reCAPTCHA.AspNetCore#80]
Implementing it in a Ajax Form is not working as expected.
Sometimes the #g-recaptcha-response input isn't filled and sometimes it is. And when the #g-recaptcha-response is filled my model says it's invalid. Does it even work wit a Ajax Form?

**Comment by TimothyMeadows** [comment]
This would depend on the version you are using. For example V2Invis has a SuccessCallback you register a function name too, and it will attempt to trigger that method with the "token" param which is the actual value of g-repactcha-response. If you get an empty token this might be related to google, or the form sitting to long before being submitted (currently unware of googles timeout time).
