### ISSUE TITLE
Implementation on Razor Pages

### ISSUE THREAD

**Issue by gokujax** [TimothyMeadows/reCAPTCHA.AspNetCore#82]
How to implement the package on Razor Pages using localhost as "Site" of RecaptchaSettings?

**Comment by TimothyMeadows** [comment]
Google does not exactly support localhost, however you can add localhost (unadvised for security reasons) to your white list in your site keys domains list. Better yet if your testing you can use the official test keys from google.

Site key: 6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI
Secret key: 6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe

These are designed for localhost use and do not require domain matching but does contain a red error message at all times about them being test keys.
