### ISSUE TITLE
Recaptcha score configurable from appsettings

### ISSUE THREAD

**Issue by armanRah** [TimothyMeadows/reCAPTCHA.AspNetCore#83]
Is there a way to get the recaptcha score from appsettings as part of Recaptcha settings. 
Like, `"RecaptchaMeasureScore":"0.5"`

**Comment by TimothyMeadows** [comment]
You can set this via the validation method, that can be set via appsettings on your own and populated into the method. The check for "score" is an optional feature with exception to scores reaching 0.0 in which google does not return a response code.
