### ISSUE TITLE
HttpClient performance issue

### ISSUE THREAD

**Issue by TimothyMeadows** [TimothyMeadows/reCAPTCHA.AspNetCore#9]
It seems there may be a bug / feature in httpclient that causes performance issues affects this library.. More can be read about this here:

https://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/
https://byterot.blogspot.com/2016/07/singleton-httpclient-dns.html

**Comment by ErikPhilips** [comment]
I'd also recommend allowing the consumer to pass their own HttpClient.

`
    public RecaptchaService(IOptions<RecaptchaSettings> options)
      this(options, null)
    {
    }
    public RecaptchaService(IOptions<RecaptchaSettings> options, HttpClient httpClient)
    {
      RecaptchaSettings = options.Value;
    }


`

**Comment by TimothyMeadows** [comment]
This is also a good enhancement. Thanks for both Erik.

**Comment by TimothyMeadows** [comment]
https://github.com/TimothyMeadows/reCAPTCHA.AspNetCore/releases/tag/2.1.3
