### ISSUE TITLE
[Q]: Can you render a full challenge in V3 if user fails the score?

### ISSUE THREAD

**Issue by maxima120** [TimothyMeadows/reCAPTCHA.AspNetCore#96]
It is similar to another question but not quite (https://github.com/TimothyMeadows/reCAPTCHA.AspNetCore/issues/72).

I use recaptcha on Register page.. 

Imagine a user failed validation. legitimately.. If I set minScore to .85 instead of .5 it is quite possible but I still want to give them chance to prove they arent bot.. In this case there is no way the user **cannot progress any further**.. 

So naturally I expect the recaptcha to change to a full challenge - a tickbox "I am no robot" or a puzzle..

I dont see how can I achieve that..

Please help

**Comment by TimothyMeadows** [comment]
Hi, i know this a late response, however the detection method is, in a way ultimately controlled by Google. This includes how many images are shown (I.E. the largest ones that ask for multiple pages of images).

However, you can technically move between versions using this library. If you see that a user has failed, and you want to revert to the checkbox auth for them to give them another chance. You might consider adding code that let's you swap between v2, and v3 renders, where v3 is used by default, and v2 is used after the user fails and a re-post is requested.

I do not have an examples of this, but there isn't any reason it can't be done this way in theory.

**Comment by TimothyMeadows** [comment]
Closing, re-open if you feel you need more help.
